"""Bundle every JSON listed in manifest.json into bundle.js.

The JSON files stay the source of truth. bundle.js exists only so index.html also
works when opened straight from disk (file://), where browsers block fetch() of JSON.
Run it after editing anything in data/ or config/:  python scripts/build.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "bundle.js"


def merge(files):
    merged = {}
    for f in files:
        merged.update(json.loads((ROOT / f).read_text(encoding="utf-8")))
    return merged


def build():
    manifest = json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))
    bundle = {"data": merge(manifest["data"]), "config": merge(manifest["config"])}
    OUT.write_text(
        "// Generated by scripts/build.py from manifest.json. Do not edit; edit the JSON files instead.\n"
        "window.PKA_BUNDLE = " + json.dumps(bundle, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.name} ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    build()
